In [2]:
from osgeo import gdal
import numpy as np
import matplotlib.pyplot as  plt
import numpy as np

In [3]:
dataset=gdal.Open(r"C:\Users\86157\Desktop\微信图片_20220513175549.jpg")

In [4]:
width=dataset.RasterXSize
height=dataset.RasterYSize
proj=dataset.GetProjection()
Geotrans=dataset.GetGeoTransform()
bands=dataset.RasterCount
print(bands)

1


In [5]:
print(proj)

In [6]:
im_data=dataset.ReadAsArray()
print(im_data)

[[248 248 248 ... 248 248 248]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [20]:
print(im_data.shape)

(647, 649)


In [7]:
desc = dataset.GetDescription()   
# print(desc)
# print(dataset.GetMetadata())

In [8]:
r=dataset.GetRasterBand(1)
gdal.GetDataTypeName(r.DataType)

'Byte'

###  滤波

In [9]:
# kenel=np.array([[1/9,1/9,1/9],[1/9,1/9,1/9],[1/9,1/9,1/9]])
kenel=np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]])
# gx=np.array([[-1,0,1],[-2,0,2],[-1,0,1]])
# gy=np.array([[1,2,1],[0,0,0],[-1,-2,-1]])
temp=im_data.copy()
# print(temp)
# for k in range(bands):
for i in range(1,height-1):
        for j in range(1,width-1):
            cell=0
            for m in range(-1,2):
                for n in range(-1,2):
                    cell+=temp[i+m][j+n]*kenel[m+1][n+1]
            if cell<0:
                im_data[i][j]=0
            if cell>0:
                im_data[i][j]=255
            else:
                im_data[i][j]=cell
            



In [10]:
print(im_data)

[[248 248 248 ... 248 248 248]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255   0   0 ...   0   0 255]
 [255   0   0 ...   0   0 255]
 [255 255 255 ... 255 255 255]]


In [11]:
driver=gdal.GetDriverByName('GTiff')
new_dataset=driver.Create(r'C:\Users\86157\Desktop\3.tif',width,height,1,gdal.GDT_Byte)
new_dataset.SetGeoTransform(Geotrans)
new_dataset.SetProjection(proj)
# for i in range(bands):
new_dataset.GetRasterBand(1).WriteArray(im_data)
del new_dataset